# This script sorts the processes on the basis of the RSS
# This script would take the input from the ProcessList generated by SaveFilter.sh

sh SaveFilter.sh
echo -e "User asked to sort the processes on the basis of RSS on" `date` >> LOG

printf "%-5s\t%-5s\t%-8s\t%-8s\t%-8s\t%-5s\t%-5s\t%-16s\t%-10s\n" "PID" "STAT" "VSZ" "RSS" "SZ" "%CPU" "%MEM" "Command" "User"

sort -n +3 -4 < ProcessList

